[build]
target = "index.html"

[serve]
ignore = []
on_rebuild = ["cls"]
[[serve.static_dirs]]
dir = "../assets"

##[[hooks]]
##stage = "build"
##command = "xcopy"
##command_arguments = ["assets", "dist", "/E", "/I", "/Y"]
