[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.27.0"
futures-util = "0.3"
serde_json = "1.0.140"
